name: tourpedia
description: "Alterra Prakerja 2024"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_staggered_animations: ^1.1.1
  intl: ^0.19.0
  map_launcher: ^3.3.1

  flutter_notion_avatar: ^0.0.4
  widgets_to_image: ^1.0.0
  
  delayed_widget: ^1.1.2
  connectivity_plus: ^6.0.4
  auto_size_text: ^3.0.0
  bounce: ^1.0.2
  
  smooth_page_indicator: ^1.1.0
  extended_image: ^8.2.1

  carousel_slider: ^4.2.1

  
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1

  video_player: ^2.9.1
  dotted_border: ^2.1.0

  permission_handler: ^11.3.1

  sliding_clipped_nav_bar: ^3.1.1

  quickly: ^5.7.0
  vaultify: ^1.2.0


  equatable:

  #  parallax_rain: ^1.1.1
  filter_list: ^1.0.3
  flutter_osm_plugin: ^1.2.0

  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  flutter_expandable_fab: ^2.2.0
  connectivity_widget: ^3.0.0
  flutter_emoji_feedback: ^0.3.2
  refreshed: ^2.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11


flutter:

  #
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/destination/
    - assets/lotties/
    - assets/videos/

  fonts:
    - family: poppins_regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppins_medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: poppins_semi_bold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: poppins_bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
